### PR TITLE
General 1.4.1 fixes

### PR DESCRIPTION
**Pull request by feitnomore**

### CODE REVIEW

**Comment by puru786** [comment]
Hello, I downloaded the latest update and the images add section is busted after the new update. I can go the url/imagelist manually but when I try to add the image link, the namespace selector is not populating the values. 
When I inspect the image page in the browser it gives a 404 error.

**Comment by feitnomore** [comment]
Did you update the YAMLs as well? You need to apply the bundled yaml, or the separate yamls as there are changes to roles and custom resource definitions.
In case yes, please, provide some screenshots for me on the inspect, as in my environment, this seems to work fine.
THANKS

**Comment by thisLambo** [comment]
> Hello, I downloaded the latest update and the images add section is busted after the new update. I can go to the url/imagelist manually but when I try to add the image link, the namespace selector is not populating the values. When I inspect the image page in the browser it gives a 404 error.

I had the same issue, don't know if you solved it but the [`crd.yaml`](https://raw.githubusercontent.com/kubevirt-manager/kubevirt-manager/refs/heads/main/kubernetes/crd.yaml) file is not included in the `bundled.yaml` file

**Comment by feitnomore** [comment]
Thanks for the update @thisLambo , I'll track it on #85

**Comment by puru786** [comment]
> > Hello, I downloaded the latest update and the images add section is busted after the new update. I can go to the url/imagelist manually but when I try to add the image link, the namespace selector is not populating the values. When I inspect the image page in the browser it gives a 404 error.
> 
> I had the same issue, don't know if you solved it but the [`crd.yaml`](https://raw.githubusercontent.com/kubevirt-manager/kubevirt-manager/refs/heads/main/kubernetes/crd.yaml) file is not included in the `bundled.yaml` file

I was able to solve it but it was more of a workaround. I quickly figured the bundled file was missing the CRD file. So after applying the bundled file I also apply the CRD file and that solves the issue for me.

**Comment by feitnomore** [comment]
Thank you all, I've just merged a new version with this fix.

**Pull request merged**
